version: '3'

services:
  api:
    container_name: "snippets-api"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: "${GITHUB_ACTOR}"
        TOKEN: "${GITHUB_TOKEN}"
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      PORT: "${PORT}"
      PRINTSCRIPT_URL: "${PRINTSCRIPT_URL}"

  db:
    container_name: snippets-db
    image: postgres:15
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
