name: "Continuous Deployment to Dev"
on:
  workflow_run:
    workflows: ["Continuous Integration for Dev"]
    types:
      - completed

jobs:
  deploy_dev:
    name: Deploy Docker Image to Dev VM
    runs-on: ubuntu-latest

    steps:
      - name: Update service on VM with new image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          script: |
            pwd
            cd infra
            echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login -u ${{ github.actor }} --password-stdin ghcr.io 
            sudo docker-compose -f docker-compose.dev.yml pull snippets
            sudo docker-compose -f docker-compose.dev.yml up -d snippets

