name: "Continuous Deployment to Prod"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    deploy_prod:
      name: Deploy Docker Image to Prod VM
      runs-on: ubuntu-latest

      steps:
        - name: Update service on Prod VM with new image
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.VM_HOST_PROD }}
            username: ${{ secrets.VM_USER }}
            key: ${{ secrets.VM_KEY }}
            script: |
              pwd
              cd infra
              echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login -u ${{ github.actor }} --password-stdin ghcr.io
              sudo docker-compose -f docker-compose.prod.yml pull snippets
              sudo docker-compose -f docker-compose.prod.yml up -d snippets

